# Generated by Django 2.2.4 on 2020-06-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_payment_stripe_charge_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order_id',
            field=models.CharField(default='0', max_length=100, null=True),
        ),
    ]
