# Generated by Django 2.2.4 on 2020-06-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_payment_productinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=3)),
                ('phone_number', models.CharField(max_length=6)),
                ('token', models.CharField(max_length=6)),
                ('is_verified', models.BooleanField()),
            ],
        ),
    ]
